item1 = Item.create(name: "Trash", description: "Trash goes out Tuesday night.", category: "Chore")
item2 = Item.create(name: "Dishes", description: "Empty the dishwasher on monday.", category: "Chore")
item3 = Item.create(name: "Resume", description: "Update existing Resume with Flatiron info and experience.", category: "Work")
item4 = Item.create(name: "Ugh", description: "Learn Python, everyone else is doing it.", category: "Work")
item5 = Item.create(name: "null", description: "Hide the body. Maybe under neighbors porch?", category: "Muahaha")