item1 = Item.create(description: "Trash goes out Tuesday night.")
item2 = Item.create(description: "Empty the dishwasher on monday.")
item3 = Item.create(description: "Update existing Resume with Flatiron info and experience.")
item4 = Item.create(description: "Learn Python, everyone else is doing it.")
item5 = Item.create(description: "Hide the body. Maybe under neighbors porch?")